# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8d5cbd4521ecf52f570d32d9b72cf75b"
name = "local-pickup-rc"
handle = "local-pickup-rc"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,write_cart_transforms,write_delivery_customizations,unauthenticated_read_product_pickup_locations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
